spring:
  application:
    name: friendexam

  datasource:
    url: jdbc:mysql://localhost:3306/exampledb
    username: carami
    password: kang1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80